Repository DnD-Montreal/session-tome, pull requests merged in 2021-11, with the labels that each got.

#144 DM Entry Controller
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Observers/EntryObserver.php
  routes/web.php
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: task, back end

#103 Add page for character detail view
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
  resources/js/Components/CharacterDetail/index.ts
  resources/js/Components/Table/CharacterDetail/CharacterDetailTable.test.js
  resources/js/Components/Table/CharacterDetail/CharacterDetailTable.tsx
  resources/js/Components/Table/CharacterDetail/TableToolbar.tsx
  resources/js/Components/Table/CharacterDetail/index.ts
  resources/js/Components/index.ts
  resources/js/Pages/Character/Detail/CharacterDetail.test.js
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Detail/index.ts
  resources/mock/character-detail-data.tsx
Labels: enhancement, front end

#147 Character create, edit integration with backend
  .eslintrc.json
  .prettierrc.json
  app/Exceptions/Handler.php
  app/Http/Controllers/AdventuresLeagueImportController.php
  app/Http/Controllers/BeyondImportController.php
  app/Http/Controllers/CharacterController.php
  app/Http/Middleware/Authenticate.php
  app/Http/Requests/CharacterStoreRequest.php
  app/Http/Requests/CharacterUpdateRequest.php
  database/seeders/DatabaseSeeder.php
  package.json
  resources/js/Components/DeleteModal/DeleteModal.tsx
  resources/js/Components/DeleteModal/index.ts
  resources/js/Components/ErrorText/ErrorText.test.js
  resources/js/Components/ErrorText/ErrorText.tsx
  resources/js/Components/ErrorText/index.ts
  resources/js/Components/FactionChip/FactionChip.test.js
  resources/js/Components/FactionChip/FactionChip.tsx
  resources/js/Components/Form/CharacterCreateForm.test.js
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/LoginForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/index.ts
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Error.tsx
  resources/js/Pages/Test/Test.test.js
  resources/js/Pages/Test/Test.tsx
  resources/js/Pages/Test/index.ts
  resources/js/Types/character-row-data.ts
  resources/js/Types/global.ts
  resources/lang/en/auth.php
  routes/web.php
  tests/Feature/AuthenticationTest.php
  tests/Feature/Http/Controllers/AdventuresLeagueImportControllerTest.php
  tests/Feature/Http/Controllers/BeyondImportControllerTest.php
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: task, back end, front end

#156 Integrate character import up with backend
  database/migrations/2021_11_04_231857_add_cascades_to_entries_table.php
  resources/js/Components/Form/CharacterImportForm.test.js
  resources/js/Components/Form/CharacterImportForm.tsx
Labels: task, back end, front end

#155 128 Character Management Cypress End-to-End Tests
  .env.cypress
  .github/workflows/test-suite.yml
  cypress/integration/character_management.js
  package.json
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  yarn.lock
Labels: test

#150 118 Attach DM Entries to a Character
  app/Http/Controllers/CharacterBulkAttachDMEntryController.php
  app/Http/Requests/AttachDMEntryRequest.php
  routes/web.php
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
Labels: enhancement, back end

#160 Integrate character detail page with backend
  .husky/commit-msg
  .husky/pre-commit
  app/Http/Controllers/CharacterController.php
  app/Models/Entry.php
  resources/js/Components/Authentication/Authentication.test.js
  resources/js/Components/Authentication/Authentication.tsx
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
  resources/js/Components/DeleteModal/DeleteModal.tsx
  resources/js/Components/EditDrawer/EditDrawer.tsx
  resources/js/Components/ErrorText/ErrorText.test.js
  resources/js/Components/ErrorText/ErrorText.tsx
  resources/js/Components/FactionChip/FactionChip.test.js
  resources/js/Components/FactionChip/FactionChip.tsx
  resources/js/Components/Form/CharacterCreateForm.test.js
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/LoginForm.test.js
  resources/js/Components/Form/LoginForm.tsx
  resources/js/Components/Form/RegistrationForm.test.js
  resources/js/Components/Form/RegistrationForm.tsx
  resources/js/Components/Form/index.ts
  resources/js/Components/RarityChip/RarityChip.tsx
  resources/js/Components/Table/CharacterDetail/CharacterDetailTable.test.js
  resources/js/Components/Table/CharacterDetail/CharacterDetailTable.tsx
  resources/js/Components/Table/CharacterDetail/TableToolbar.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.test.js
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/Table/ItemTable/ItemTable.test.js
  resources/js/Components/Table/ItemTable/ItemTable.tsx
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.test.js
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Character/Character.test.js
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Create/CharacterCreate.test.js
  resources/js/Pages/Character/Create/CharacterCreate.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.test.js
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Import/CharacterImport.tsx
  resources/js/Pages/Error.tsx
  resources/js/Pages/Item/Item.test.js
  resources/js/Pages/Item/Item.tsx
  resources/js/Pages/Welcome.tsx
  resources/js/Types/character-data.ts
  resources/js/Types/entries-data.ts
  resources/js/Utils/index.ts
  resources/js/app.js
  resources/mock/entries-data.ts
  resources/mock/event-data.ts
  tests/Feature/Http/Controllers/CharacterControllerTest.php
Labels: task, back end, front end

#170 General re-size fix + Edit form privacy setting pre-fill not working
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.css
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
Labels: bug, chore, front end

#171 test: #168 Add cypress tests to character exploration story
  cypress/integration/character_exploration.js
  cypress/integration/test.js
Labels: test

#173 Add cypress test for character log migrator story
  cypress/integration/character_exploration.js
  cypress/integration/character_log_migrator.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: test

#187 Add item creation when storing Entries
  .husky/commit-msg
  .husky/pre-commit
  app/Actions/CreateEntryItems.php
  app/Http/Controllers/EntryController.php
  app/Http/Controllers/ItemController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Http/Requests/ItemStoreRequest.php
  app/Http/Requests/ItemUpdateRequest.php
  app/Models/Item.php
  composer.json
  composer.lock
  database/factories/ItemFactory.php
  database/migrations/2021_09_23_221026_create_items_table.php
  database/migrations/2021_11_22_201558_add_nullables_to_items_table.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
  tests/Feature/Http/Controllers/ItemControllerTest.php
  tests/Unit/Actions/CreateEntryItemsTest.php
Labels: enhancement, task, back end

#177 adventures league import bug fix
  app/Services/AdventuresLeagueAdapter.php
  database/migrations/2021_09_23_221026_create_items_table.php
  database/mocks/dante-bad.csv
  database/mocks/dante.csv
  tests/Feature/Http/Controllers/AdventuresLeagueImportControllerTest.php
Labels: bug, back end

#189 Custom data table component
  resources/css/app.css
  resources/js/Components/Atom/DataTable.test.js
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Components/Atom/Link.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/CharacterImportForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.test.js
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Character/Character.test.js
  resources/js/Pages/Character/Character.tsx
  resources/js/Utils/index.ts
  resources/js/Utils/table-constant.ts
Labels: enhancement, front end

#191 190 item import fix
  app/Services/AdventuresLeagueAdapter.php
Labels: chore, back end, refactor

#197 179 registration and login cypress tests
  cypress/integration/Authentication/authentication.js
  cypress/integration/Character Management/character_exploration.js
  cypress/integration/Character Management/character_log_migrator.js
  cypress/integration/Character Management/character_management.js
  cypress/support/commands.js
Labels: test

#192 Clean up component folder
  resources/js/Components/Atom/Drawer.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Chips/FactionChip/FactionChip.test.js
  resources/js/Components/Chips/FactionChip/FactionChip.tsx
  resources/js/Components/Chips/FactionChip/index.ts
  resources/js/Components/Chips/RarityChip/RarityChip.tsx
  resources/js/Components/Chips/RarityChip/index.ts
  resources/js/Components/Chips/index.ts
  resources/js/Components/EditDrawer/index.ts
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/Table/ItemTable/ItemTable.tsx
  resources/js/Components/Table/index.ts
  resources/js/Components/index.ts
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
Labels: front end, refactor
