Repository DnD-Montreal/session-tome, pull requests merged in 2021-09, with the labels that each got.

#14 Add issue templates for bugs, stories, and tasks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: documentation, chore

#17 Add and setup cypress to the project
  .env.cypress
  composer.json
  composer.lock
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/1-getting-started/todo.spec.js
  cypress/integration/2-advanced-examples/actions.spec.js
  cypress/integration/2-advanced-examples/aliasing.spec.js
  cypress/integration/2-advanced-examples/assertions.spec.js
  cypress/integration/2-advanced-examples/connectors.spec.js
  cypress/integration/2-advanced-examples/cookies.spec.js
  cypress/integration/2-advanced-examples/cypress_api.spec.js
  cypress/integration/2-advanced-examples/files.spec.js
  cypress/integration/2-advanced-examples/local_storage.spec.js
  cypress/integration/2-advanced-examples/location.spec.js
  cypress/integration/2-advanced-examples/misc.spec.js
  cypress/integration/2-advanced-examples/navigation.spec.js
  cypress/integration/2-advanced-examples/network_requests.spec.js
  cypress/integration/2-advanced-examples/querying.spec.js
  cypress/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  cypress/integration/2-advanced-examples/traversal.spec.js
  cypress/integration/2-advanced-examples/utilities.spec.js
  cypress/integration/2-advanced-examples/viewport.spec.js
  cypress/integration/2-advanced-examples/waiting.spec.js
  cypress/integration/2-advanced-examples/window.spec.js
  cypress/plugins/index.js
  cypress/plugins/swap-env.js
  cypress/support/assertions.js
  cypress/support/commands.js
  cypress/support/index.js
  cypress/support/laravel-commands.js
  cypress/support/laravel-routes.js
  package.json
  yarn.lock
Labels: task, chore

#15 chore: #12 add back end linter
  .gitignore
  composer.json
  composer.lock
Labels: chore

#19 Update ReadMe
  CONTRIBUTING.md
  README.md
Labels: documentation

#23 Invalid path for .eslintignore
  .eslintignore
Labels: bug
