Repository DnD-Montreal/session-tome, pull requests merged in 2022-01, with the labels that each got.

#223 Link button not clickable outside of text
  resources/js/Components/Atom/Link.tsx
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/CharacterImportForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Character/Character.test.js
Labels: bug

#224 Data table buttons look off when on smaller viewport
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
Labels: bug

#226 Login text to prompt popover
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
Labels: bug

#231 Add re-usable stepper form component
  resources/js/Components/Atom/StepperForm.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
Labels: enhancement, front end

#232 Filter rating index
  app/Http/Controllers/RatingController.php
  app/Models/Session.php
  app/Models/User.php
  database/factories/SessionFactory.php
  database/migrations/2021_09_23_221032_create_campaigns_table.php
  database/migrations/2022_01_06_045931_add_language_to_sessions_table.php
  tests/Feature/Http/Controllers/RatingControllerTest.php
  tests/Unit/Models/UserTest.php
Labels: enhancement, back end

#221 Install/Setup Laravel Backpack
  .gitignore
  README.md
  app/Exceptions/Handler.php
  app/Http/Controllers/Admin/AdventureCrudController.php
  app/Http/Controllers/Admin/CampaignCrudController.php
  app/Http/Controllers/Admin/CharacterCrudController.php
  app/Http/Controllers/Admin/EntryCrudController.php
  app/Http/Controllers/Admin/EventCrudController.php
  app/Http/Controllers/Admin/ItemCrudController.php
  app/Http/Controllers/Admin/LeagueCrudController.php
  app/Http/Controllers/Admin/RatingCrudController.php
  app/Http/Controllers/Admin/RoleCrudController.php
  app/Http/Controllers/Admin/SessionCrudController.php
  app/Http/Controllers/Admin/TradeCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Middleware/CheckIfAdmin.php
  app/Http/Requests/AdventureRequest.php
  app/Http/Requests/CampaignRequest.php
  app/Http/Requests/CharacterRequest.php
  app/Http/Requests/EntryRequest.php
  app/Http/Requests/EventRequest.php
  app/Http/Requests/ItemRequest.php
  app/Http/Requests/LeagueRequest.php
  app/Http/Requests/RatingRequest.php
  app/Http/Requests/RoleRequest.php
  app/Http/Requests/SessionRequest.php
  app/Http/Requests/TradeRequest.php
  app/Http/Requests/UserRequest.php
  app/Models/Adventure.php
  app/Models/Campaign.php
  app/Models/Character.php
  app/Models/Entry.php
  app/Models/Event.php
  app/Models/Item.php
  app/Models/League.php
  app/Models/Rating.php
  app/Models/Role.php
  app/Models/Session.php
  app/Models/Trade.php
  app/Models/User.php
  app/Providers/RouteServiceProvider.php
  composer.json
  composer.lock
  config/backpack/base.php
  config/backpack/crud.php
  config/gravatar.php
  database/seeders/RoleSeeder.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/base/inc/topbar_left_content.blade.php
  resources/views/vendor/backpack/base/inc/topbar_right_content.blade.php
  routes/backpack/custom.php
  routes/web.php
  tests/Feature/BackPackControllerTest.php
Labels: enhancement, back end

#236 Add Rating Report Generation
  app/Actions/GenerateRatingReport.php
  app/Actions/StreamCsvFile.php
  app/Http/Controllers/Admin/UserCrudController.php
  database/factories/AdventureFactory.php
  database/factories/LeagueFactory.php
  database/seeders/DatabaseSeeder.php
  resources/views/vendor/backpack/crud/buttons/rating_report.blade.php
  routes/web.php
  tests/Unit/Actions/GenerateRatingReportTest.php
  tests/Unit/Actions/StreamCsvFileTest.php
Labels: enhancement, task, back end

#239 Fix Item Entry Edit Bug
  app/Actions/CreateEntryItems.php
Labels: bug, back end

#230 Add missing fields for DM Entry details
  app/Http/Controllers/DMEntryController.php
  app/Http/Requests/EntryStoreRequest.php
  resources/js/Components/Atom/StepperForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/ItemCreateForm.tsx
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Pages/Entry/Create/DmEntryCreate.tsx
  resources/js/Types/entries-data.ts
Labels: enhancement, front end

#275 Fix Integrity Constraint Error When Deleting Characters
  app/Models/User.php
  app/Observers/CharacterObserver.php
  app/Observers/EntryObserver.php
  app/Providers/EventServiceProvider.php
  database/migrations/2022_01_12_015440_add_cascades_to_items_table.php
  database/migrations/2022_01_12_021419_add_soft_deletes_to_users_table.php
  database/seeders/DatabaseSeeder.php
  tests/Feature/Http/Controllers/UserControllerTest.php
  tests/Unit/Models/UserTest.php
  tests/Unit/Observers/CharacterObserverTest.php
Labels: bug, back end

#277 Data table search bar not filtering correctly
  resources/js/Components/Atom/DataTable.tsx
Labels: bug, front end

#276 Add day js for formatting
  package.json
  resources/js/Components/Table/CharacterTable/CharacterTable.test.js
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  yarn.lock
Labels: enhancement, front end

#283 Item form refactor
  package.json
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/ItemCreateForm.tsx
  resources/js/Components/Form/ItemForm.tsx
  yarn.lock
Labels: enhancement, front end, refactor

#284 Capitalize public/private status that appears on the character detail page
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
Labels: bug, front end

#290 Implement conditional button rendering for Character Detail page
  .eslintrc.json
  resources/__mocks__/@inertiajs/inertia-react.js
  resources/js/Components/CharacterDetail/CharacterDetailBox.test.js
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
  resources/js/Utils/index.ts
  resources/js/Utils/use-user.ts
Labels: bug, front end

#288 Adjusting Session Tome color palette
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
Labels: bug, task, front end

#289 GP inputs allow floats
  resources/js/Components/Form/DmEntryCreateForm.tsx
Labels: bug, front end

#281 Modify Campaign Model
  app/Models/Campaign.php
  app/Models/User.php
  app/Observers/CampaignObserver.php
  app/Providers/EventServiceProvider.php
  database/migrations/2022_01_13_212435_add_code_to_campaigns_table.php
  database/migrations/2022_01_14_201203_add_is_dm_to_campaign_user_table.php
  tests/Unit/Models/UserTest.php
  tests/Unit/Observers/CampaignObserverTest.php
Labels: enhancement, back end

#291 Item Tier bug
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: bug, back end

#279 #181 Character Actions Flow Improvements
  app/Http/Controllers/CharacterController.php
  cypress.json
  cypress/integration/Character Management/character_management.js
  resources/js/Components/Form/CharacterCreateForm.test.js
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Create/CharacterCreate.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  tests/Feature/Http/Controllers/CharacterControllerTest.php
Labels: front end, design

#237 Character detail entry form
  app/Http/Controllers/CharacterController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Models/Entry.php
  app/Models/Rating.php
  resources/js/Components/Atom/StepperForm.tsx
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.test.js
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Form/RatingForm.tsx
  resources/js/Components/Form/index.ts
  resources/js/Components/index.ts
  resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
  resources/js/Pages/Character/Detail/Entry/Create/index.ts
  resources/js/Pages/Character/Detail/index.ts
  resources/js/Types/entries-data.ts
  resources/js/Types/rating-data.ts
  tests/Feature/Http/Controllers/EntryControllerTest.php
  tests/Unit/Models/EntryTest.php
Labels: enhancement, task, front end

#300 Magic items column missing from DM entries table and entries table
  app/Http/Controllers/DMEntryController.php
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Utils/formatter.ts
  resources/js/Utils/index.ts
Labels: bug, front end

#280 Campaign Entry Observer Logic
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  app/Observers/EntryObserver.php
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
  tests/Unit/Observers/EntryObserverTest.php
Labels: enhancement, back end

#299 Rating Index
  app/Http/Controllers/RatingController.php
  resources/js/Components/Table/RatingTable/RatingTable.test.js
  resources/js/Components/Table/RatingTable/RatingTable.tsx
  resources/js/Components/Table/RatingTable/index.ts
  resources/js/Components/Table/index.ts
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Rating/Rating.test.js
  resources/js/Pages/Rating/Rating.tsx
  resources/js/Pages/Rating/index.ts
  resources/js/Types/reported-rating-data.ts
  resources/mock/rating-data.ts
  tests/Feature/Http/Controllers/RatingControllerTest.php
Labels: enhancement, task, front end

#301 Add Deploy Workflow
  .github/workflows/deploy.yml
Labels: task, dev ops

#297 Sort Entries by Date Played
  app/Http/Controllers/CharacterController.php
  app/Models/Entry.php
  tests/Unit/Models/EntryTest.php
Labels: bug, back end

#294 Campaign Filtering By Current User
  app/Http/Controllers/CampaignController.php
Labels: back end

#292 Event Report Generation
  app/Actions/GenerateEventReport.php
  app/Http/Controllers/Admin/EventCrudController.php
  app/Models/Character.php
  resources/views/vendor/backpack/crud/buttons/event_report.blade.php
  routes/backpack/custom.php
  tests/Unit/Actions/GenerateEventReportTest.php
  tests/Unit/Models/CharacterTest.php
Labels: enhancement, back end

#310 Preserve scroll on rating index table upon filter
  resources/js/Components/Table/RatingTable/RatingTable.tsx
Labels: bug, front end

#298 Front-end code standard pass
  .github/workflows/test-suite.yml
  app/Actions/CreateAndAttachRating.php
  app/Http/Controllers/CharacterController.php
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Observers/EntryObserver.php
  database/factories/AdventureFactory.php
  package.json
  resources/js/Components/Atom/Drawer.tsx
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.test.js
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Form/ItemEditForm.tsx
  resources/js/Components/Form/ItemForm.tsx
  resources/js/Components/Form/RatingForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.test.js
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.test.js
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/Table/ItemTable/ItemTable.test.js
  resources/js/Components/index.ts
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Create/CharacterCreate.test.js
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/DMEntry/DMEntry.tsx
  resources/js/Pages/Entry/Create/DmEntryCreate.tsx
  resources/js/Pages/Item/Item.tsx
  resources/js/Utils/option-constants.ts
  resources/js/Utils/use-edit-drawer.ts
  resources/js/ziggy.js
  tests/Feature/Http/Controllers/EntryControllerTest.php
  tsconfig.json
  webpack.config.js
Labels: enhancement, front end

#331 Item delete fix
  app/Http/Controllers/ItemController.php
  resources/js/Components/Table/ItemTable/ItemTable.test.js
  resources/js/Components/Table/ItemTable/ItemTable.tsx
  tests/Feature/Http/Controllers/ItemControllerTest.php
Labels: bug, back end, front end

#328 Rating buttons in EntryCreateForm overlap on smaller screen
  resources/js/Components/Form/RatingForm.tsx
Labels: bug, front end

#323 Adventure field type ahead
  app/Http/Controllers/CharacterController.php
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Models/Adventure.php
  app/Models/Traits/Filterable.php
  app/Models/User.php
  resources/js/Components/Atom/Autocomplete.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/index.ts
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: enhancement, task, back end, front end

#327 Fix entry fields saving / displaying improperly
  app/Http/Controllers/BulkAttachController.php
  app/Http/Controllers/DMEntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Models/Entry.php
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Types/entries-data.ts
  routes/web.php
Labels: bug, back end, front end

#305 Create Campaign Join Endpoint
  app/Http/Controllers/CampaignController.php
  app/Http/Controllers/CampaignRegistrationController.php
  app/Http/Requests/CampaignStoreRequest.php
  resources/js/Pages/Campaign/Campaign.test.js
  resources/js/Pages/Campaign/Campaign.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.test.js
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Pages/Campaign/Detail/index.ts
  resources/js/Pages/Campaign/index.ts
  routes/web.php
  tests/Feature/Http/Controllers/CampaignControllerTest.php
  tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php
Labels: enhancement, back end

#325 Disable scroll for numerical inputs in forms
  resources/js/Components/Atom/NumberInput.tsx
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.test.js
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Form/ItemEditForm.test.js
  resources/js/Components/Form/ItemEditForm.tsx
  resources/js/Components/Form/ItemForm.tsx
  resources/js/Components/index.ts
  resources/js/Utils/option-constants.ts
Labels: bug, front end

#333 Create Cypress Tests for Magic Item Inventory Management
  app/Http/Controllers/ItemController.php
  cypress/integration/Character Management/item_management.js
  cypress/support/commands.js
  database/seeders/FastSeeder.php
  docker-compose.yml
  resources/js/Pages/Item/Detail/ItemDetail.tsx
  tests/Feature/Http/Controllers/ItemControllerTest.php
Labels: test

#349 Cypress Tests for Item Entry Management
  cypress/integration/Game Session Tracking/item_entry_management.js
Labels: test

#352 Create Cypress Tests for Admin Event Control
  .github/workflows/test-suite.yml
  cypress/integration/Event Management/admin_event_crud.js
Labels: test, dev ops

#351 Create Cypress Tests for DM Entry Management
  app/Http/Controllers/RatingController.php
  app/Http/Requests/EntryUpdateRequest.php
  cypress/integration/Game Session Tracking/dm-entry-management.js
  resources/js/Pages/DMEntry/DMEntry.tsx
Labels: test

#357 Create Cypress Tests for Rating Lookup
  cypress/integration/Player Rating System/rating_lookup.js
Labels: test

#354 Create Cypress Tests for Bulk Entry Creation
  cypress/integration/Game Session Tracking/bulk_entry_creation.js
Labels: test

#355 Create Cypress Tests for Game Master Ratings
  cypress/integration/Player Rating System/game_master_ratings.js
Labels: test

#346 Create Cypress Tests for Manage Entries
  cypress/integration/Game Session Tracking/entry_management.js
Labels: test
