Repository DnD-Montreal/session-tome, pull requests merged in 2022-03, with the labels that each got.

#464 Character detail to use correct edit entry form
  app/Http/Controllers/CharacterController.php
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
Labels: bug, back end, front end

#466 Implement Translation for Event Pages
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Table/EventTable/EventTable.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Event/Event.tsx
Labels: enhancement, front end

#465 Add default layout and progress bar
  package.json
  public/translation_en.json
  resources/js/Pages/Campaign/Campaign.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Create/CharacterCreate.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Detail/Entry/Create/BulkEntryCreate.tsx
  resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
  resources/js/Pages/Character/Import/CharacterImport.tsx
  resources/js/Pages/DMEntry/DMEntry.tsx
  resources/js/Pages/Entry/Create/DmEntryCreate.tsx
  resources/js/Pages/Item/Detail/ItemDetail.tsx
  resources/js/Pages/Item/Item.tsx
  resources/js/Pages/Profile.tsx
  resources/js/Pages/Rating/Rating.tsx
  resources/js/Pages/Trade/Trade.tsx
  resources/js/Pages/Welcome.tsx
  resources/js/app.js
  yarn.lock
Labels: enhancement, front end

#453 Campaign details connect backend
  app/Http/Controllers/CampaignController.php
  app/Http/Requests/CampaignUpdateRequest.php
  package.json
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.test.js
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Components/Form/CampaignCreateForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Pages/Campaign/Campaign.test.js
  resources/js/Pages/Campaign/Detail/CampaignDetail.test.js
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Types/campaign-data.ts
  resources/js/Types/gamemaster-data.ts
  resources/js/Types/user-character-data.ts
  resources/js/Utils/use-url-params.ts
  resources/mock/campaign-data.ts
  resources/mock/user-character-data.ts
  tests/Feature/Http/Controllers/CampaignControllerTest.php
  yarn.lock
Labels: enhancement, front end

#471 Remove last url dependency between tests
  cypress/integration/Event Management/admin_event_crud.js
Labels: test

#467 Add Event filters and accessor to Model
  app/Models/Entry.php
  app/Models/Event.php
  tests/Unit/Models/EventTest.php
Labels: enhancement, back end, priority

#405 Modify backpack to allow league admin event control
  app/Http/Controllers/Admin/AdventureCrudController.php
  app/Http/Controllers/Admin/CampaignCrudController.php
  app/Http/Controllers/Admin/CharacterCrudController.php
  app/Http/Controllers/Admin/EntryCrudController.php
  app/Http/Controllers/Admin/EventCrudController.php
  app/Http/Controllers/Admin/ItemCrudController.php
  app/Http/Controllers/Admin/LeagueCrudController.php
  app/Http/Controllers/Admin/RatingCrudController.php
  app/Http/Controllers/Admin/RoleCrudController.php
  app/Http/Controllers/Admin/SessionCrudController.php
  app/Http/Controllers/Admin/TradeCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/Traits/Accessible.php
  app/Http/Middleware/CheckIfAdmin.php
  app/Http/Requests/EventRequest.php
  app/Http/Requests/SessionRequest.php
  app/Models/User.php
  resources/views/errors/403.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  tests/Feature/BackPackControllerTest.php
  tests/Unit/Models/UserTest.php
Labels: enhancement, back end

#477 Trade Creation Backpack Bug Fix
  app/Http/Requests/TradeRequest.php
Labels: bug, back end

#478 Connecting Join Form to Backend
  app/Http/Controllers/CampaignController.php
  app/Http/Controllers/CampaignRegistrationController.php
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/CampaignJoinModal/CampaignJoinModal.test.js
  resources/js/Components/CampaignJoinModal/CampaignJoinModal.tsx
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Components/Form/CampaignCreateForm.tsx
  resources/js/Components/Form/CampaignRegistrationForm/CampaignRegistrationForm.tsx
  resources/js/Components/Form/CampaignRegistrationForm/CampaignResgistrationForm.test.js
  resources/js/Components/Table/CampaignTable/CampaignTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Pages/Campaign/Create/CampaignCreate.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.test.js
  resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.test.js
  resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.tsx
  resources/js/Types/entries-data.ts
Labels: enhancement, back end, front end

#475 Campaign Kick Endpoint
  app/Http/Controllers/CampaignRegistrationController.php
  routes/web.php
  tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php
Labels: enhancement, back end

#474 Adventures League Import Response Bug Fix
  app/Exceptions/ImportException.php
  app/Http/Controllers/AdventuresLeagueImportController.php
  app/Services/AdventuresLeagueAdapter.php
  tests/Feature/Http/Controllers/AdventuresLeagueImportControllerTest.php
  tests/Unit/Adapters/AdventuresLeagueTest.php
Labels: bug, back end

#481 Filter event controller index results
  app/Http/Controllers/EventController.php
  app/Models/Session.php
  database/factories/TradeFactory.php
  tests/Feature/Http/Controllers/EventControllerTest.php
Labels: enhancement, task, back end

#480 Data table filter reset
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Pages/Profile.tsx
Labels: bug, front end

#488 Fix validation rules for Campaigns
  app/Http/Controllers/CampaignController.php
  app/Http/Requests/CampaignStoreRequest.php
  app/Http/Requests/CampaignUpdateRequest.php
  app/Models/Campaign.php
  tests/Feature/Http/Controllers/CampaignControllerTest.php
Labels: bug, back end

#490 Filter registered sessions on event detail page
  app/Http/Controllers/EventController.php
  app/Models/Session.php
  resources/js/Pages/Event/Detail/EventDetail.test.js
  resources/js/Pages/Event/Detail/EventDetail.tsx
  resources/js/Pages/Event/Detail/index.ts
  tests/Feature/Http/Controllers/EventControllerTest.php
  tests/Unit/Models/SessionTest.php
Labels: task, back end

#491 Campaign Kick
  .prettierrc.json
  app/Http/Controllers/CampaignRegistrationController.php
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Components/CampaignKickModal/CampaignKickModal.tsx
  resources/js/Components/CampaignKickModal/index.ts
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Components/index.ts
  resources/js/Pages/Profile.tsx
  resources/js/ziggy.js
Labels: back end, front end

#494 Add campaign kick unit tests
  resources/js/Components/CampaignKickModal/CampaignKickModal.test.js
  resources/js/Components/CampaignKickModal/CampaignKickModal.tsx
Labels: front end, test

#489 Fix campaign character duplication bug
  app/Http/Controllers/CampaignRegistrationController.php
  database/migrations/2022_03_10_020408_add_unique_constraint_to_campaign_character_table.php
Labels: bug, back end

#497 refactor: modal to atom component
  resources/js/Components/Atom/Modal.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/CampaignJoinModal/CampaignJoinModal.tsx
  resources/js/Components/CampaignKickModal/CampaignKickModal.tsx
  resources/js/Components/DeleteModal/DeleteModal.tsx
  resources/js/Components/index.ts
Labels: front end, refactor

#496 Campaign detail nullable user character
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Pages/Campaign/Create/CampaignCreate.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.tsx
Labels: bug, front end

#495 Fix redirects for campaign registration
  app/Http/Controllers/CampaignRegistrationController.php
  tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php
Labels: bug, back end

#472 Event Detail and Registration
  .eslintrc.json
  app/Http/Controllers/EventController.php
  app/Http/Controllers/EventRegistrationController.php
  app/Models/Event.php
  app/Models/Session.php
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Components/Detail/EventDetailBox.tsx
  resources/js/Components/Detail/index.ts
  resources/js/Components/Modal/EventRegistrationModal.tsx
  resources/js/Components/Modal/index.ts
  resources/js/Components/Table/EventTable/EventTable.tsx
  resources/js/Components/Table/SessionTable/SessionTable.tsx
  resources/js/Components/Table/SessionTable/index.ts
  resources/js/Components/Table/index.ts
  resources/js/Components/index.ts
  resources/js/Pages/Event/Detail/EventDetail.test.js
  resources/js/Pages/Event/Detail/EventDetail.tsx
  resources/js/Pages/Event/Event.tsx
  resources/js/Types/event-data.ts
  resources/js/Types/session-data.ts
  resources/js/ziggy.js
  resources/mock/adventure-data.ts
  resources/mock/event-data.ts
  resources/mock/session-data.ts
  resources/mock/user-data.ts
  tests/Feature/Http/Controllers/EventControllerTest.php
Labels: enhancement, back end, front end

#511 Added Tests for Event Components
  resources/js/Components/Detail/EventDetailBox.test.js
  resources/js/Components/Modal/EventRegistrationModal.test.js
  resources/js/Components/Table/SessionTable/SessionTable.test.js
  resources/js/Components/Table/SessionTable/SessionTable.tsx
  resources/mock/event-data.ts
  resources/mock/session-data.ts
Labels: test

#516 Hide DM entry button when user joined a campaign with a character
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
Labels: bug, front end

#520 Hide buttons for campaign non-owners
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Types/campaign-data.ts
  resources/mock/campaign-data.ts
Labels: bug, front end

#517 Hide hard coded content
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Welcome.tsx
Labels: front end

#521 Clean up front-end files
  app/Http/Controllers/UserController.php
  resources/js/Components/Atom/ErrorText.test.js
  resources/js/Components/Atom/ErrorText.tsx
  resources/js/Components/Atom/Link.tsx
  resources/js/Components/Atom/NumberInput.tsx
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/CampaignJoinModal/index.ts
  resources/js/Components/CampaignKickModal/index.ts
  resources/js/Components/DeleteModal/index.ts
  resources/js/Components/ErrorText/index.ts
  resources/js/Components/Form/BulkEntryCreateForm.test.js
  resources/js/Components/Form/BulkEntryCreateForm.tsx
  resources/js/Components/Form/CampaignForm.test.js
  resources/js/Components/Form/CampaignForm.tsx
  resources/js/Components/Form/CampaignRegistrationForm.tsx
  resources/js/Components/Form/CampaignRegistrationForm/index.ts
  resources/js/Components/Form/CampaignResgistrationForm.test.js
  resources/js/Components/Form/CharacterForm.test.js
  resources/js/Components/Form/CharacterForm.tsx
  resources/js/Components/Form/DmEntryForm.test.js
  resources/js/Components/Form/DmEntryForm.tsx
  resources/js/Components/Form/EntryForm.test.js
  resources/js/Components/Form/EntryForm.tsx
  resources/js/Components/Form/index.ts
  resources/js/Components/Modal/CampaignJoinModal.test.js
  resources/js/Components/Modal/CampaignJoinModal.tsx
  resources/js/Components/Modal/CampaignKickModal.test.js
  resources/js/Components/Modal/CampaignKickModal.tsx
  resources/js/Components/Modal/DeleteModal.test.js
  resources/js/Components/Modal/DeleteModal.tsx
  resources/js/Components/Modal/index.ts
  resources/js/Components/index.ts
  resources/js/Pages/Campaign/Campaign.tsx
  resources/js/Pages/Campaign/Create/CampaignCreate.tsx
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Create/CharacterCreate.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
  resources/js/Pages/DMEntry/DMEntry.tsx
  resources/js/Pages/Entry/Create/DmEntryCreate.tsx
  resources/js/Pages/Profile/Profile.test.js
  resources/js/Pages/Profile/Profile.tsx
  resources/js/Pages/Profile/index.ts
  resources/js/Pages/Welcome/Welcome.tsx
  resources/js/Pages/Welcome/index.ts
  tests/Feature/Http/Controllers/UserControllerTest.php
Labels: front end, refactor

#523 Fix GM role assignment in Campaign updates
  app/Http/Controllers/CampaignController.php
  app/Http/Requests/CampaignUpdateRequest.php
  tests/Feature/Http/Controllers/CampaignControllerTest.php
Labels: bug, back end

#527 GM Entry Creation Bug Fix
  app/Exceptions/GMEntryException.php
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: back end

#528 Use prepareForValidation instead of inline controller logic
  app/Http/Controllers/BulkEntryController.php
  app/Http/Controllers/CampaignController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/BulkEntryStoreRequest.php
  app/Http/Requests/CampaignStoreRequest.php
  app/Http/Requests/CampaignUpdateRequest.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Http/Requests/FilterableRequest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: back end, refactor

#529 Create Cypress Tests for League Admin Event Crud
  cypress/integration/Event Management/league_admin_event_crud.js
  cypress/support/commands.js
  database/seeders/DatabaseSeeder.php
  database/seeders/FastSeeder.php
Labels: test

#409 Create Cypress Tests for Admin Session Control
  cypress/integration/Event Management/admin_session_crud.js
Labels: test

#526 440 player event registration cypress tests
  cypress/integration/Event Management/player_event_registration.js
  database/seeders/FastSeeder.php
  resources/js/Components/Modal/EventRegistrationModal.tsx
Labels: test

#531 Update Reward accessor to return Null
  app/Models/Entry.php
Labels: bug, back end

#535 Campaign Cypress test suite
  cypress/integration/Campaign Management/campaign_management.js
Labels: test
