Repository DnD-Montreal/session-tome, pull requests merged in 2022-06, with the labels that each got.

#546 Remove all references and secruity bypasses for locust
  app/Http/Controllers/LocustAuthController.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/Throttle.php
  routes/api.php
  tests/Feature/AuthenticationTest.php
  tests/Feature/Http/Controllers/LocustAuthControllerTest.php
Labels: chore

#548 Add Adventure importer based of CSV files
  app/Console/Commands/ImportAdventures.php
  app/Imports/AdvenutreImport.php
  app/Models/Adventure.php
  composer.json
  composer.lock
  database/factories/AdventureFactory.php
  database/migrations/2022_06_15_015700_add_tier_to_adventures_table.php
  database/mocks/test-adventures.csv
  tests/Feature/ImportAdventuresTest.php
Labels: enhancement, back end

#549 Add webkit scrollbar to the app
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
Labels: enhancement

#551 Remove sonarcloud
  .github/workflows/test-suite.yml
Labels: dev ops
