Repository DnD-Montreal/session-tome, pull requests merged in 2022-04, with the labels that each got.

#536 Cypress Tests for Campaign Enrollment
  app/Http/Controllers/CampaignRegistrationController.php
  cypress/integration/Campaign Management/campaign_enrollment.js
  database/seeders/DatabaseSeeder.php
  database/seeders/FastSeeder.php
  resources/js/Components/Table/CampaignTable/CampaignTable.tsx
Labels: task, test

#542 Hotfix: add session seats to backpack
  app/Http/Controllers/Admin/SessionCrudController.php
  database/factories/CharacterFactory.php
  database/factories/EntryFactory.php
  database/factories/SessionFactory.php
  database/seeders/DatabaseSeeder.php
Labels: bug

#545 Hide language selector when user is logged in
  resources/js/Pages/Welcome/Welcome.tsx
Labels: bug, front end
