Repository DnD-Montreal/session-tome, pull requests merged in 2022-02, with the labels that each got.

#391 Rating step skipped when the gm field is empty
  resources/js/Components/Form/EntryCreateForm.tsx
Labels: bug, front end

#390 Trade Detail Response
  app/Http/Controllers/TradeController.php
  tests/Feature/Http/Controllers/TradeControllerTest.php
Labels: back end

#400 Split cypress pipeline
  .github/workflows/test-suite.yml
Labels: dev ops

#397 Add warning related to character import
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
  resources/js/Components/Chips/FactionChip/FactionChip.tsx
  resources/js/Components/Form/CharacterImportForm.tsx
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.test.js
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/Table/ItemTable/ItemTable.test.js
  resources/js/Components/Table/ItemTable/ItemTable.tsx
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
  resources/js/app.js
  resources/mock/entries-data.ts
  resources/mock/item-data.ts
Labels: front end

#392 Gamemaster field update
  app/Http/Controllers/CharacterController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Models/Entry.php
  cypress.json
  cypress/integration/Game Session Tracking/entry_management.js
  cypress/integration/Game Session Tracking/item_entry_management.js
  cypress/integration/Player Rating System/game_master_ratings.js
  resources/js/Components/Atom/Autocomplete.tsx
  resources/js/Components/Atom/Link.tsx
  resources/js/Components/Form/BulkEntryCreateForm.test.js
  resources/js/Components/Form/BulkEntryCreateForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.test.js
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: enhancement, task, back end, front end

#398 Change Entry Update to no longer delete existing items
  app/Actions/CreateEntryItems.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: bug, back end

#396 Empty Reward Choice and Assigned Character Fields When Editing a DM Entry
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Models/Entry.php
  resources/js/Components/Detail/CharacterDetailBox.test.js
  resources/js/Components/Detail/CharacterDetailBox.tsx
  resources/js/Components/Detail/ItemDetailBox.test.js
  resources/js/Components/Detail/ItemDetailBox.tsx
  resources/js/Components/Detail/index.ts
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/ItemDetail/index.ts
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/index.ts
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: bug, back end, front end

#395 Trade index
  app/Http/Controllers/TradeController.php
  app/Models/Trade.php
  database/factories/TradeFactory.php
  resources/js/Pages/Trade/Trade.test.js
  resources/js/Pages/Trade/Trade.tsx
  resources/js/Pages/Trade/index.ts
  tests/Feature/Http/Controllers/TradeControllerTest.php
Labels: enhancement, back end

#402 User profile
  app/Http/Controllers/UserController.php
  app/Http/Requests/UserUpdateRequest.php
  app/Models/User.php
  database/migrations/2022_02_18_221110_add_language_to_users_table.php
  resources/js/Components/Authentication/Authentication.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Profile.tsx
  resources/js/Types/global.ts
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
  routes/web.php
  tests/Feature/Http/Controllers/UserControllerTest.php
Labels: enhancement, back end, front end, design

#403 Trade Fulfillment
  app/Actions/FulfillTrade.php
  app/Exceptions/TradeClosedException.php
  app/Exceptions/TradeNotAllowedException.php
  app/Http/Controllers/TradeFulfillmentController.php
  app/Http/Requests/TradeFulfillRequest.php
  app/Policies/TradePolicy.php
  app/Providers/AuthServiceProvider.php
  routes/web.php
  tests/Feature/Http/Controllers/TradeFulfillmentControllerTest.php
  tests/Unit/Actions/FulfillTradeTest.php
Labels: enhancement, back end

#411 Campaign Index and Create/Edit form
  app/Http/Controllers/CampaignController.php
  app/Http/Requests/CampaignStoreRequest.php
  resources/js/Components/Form/CampaignCreateForm.test.js
  resources/js/Components/Form/CampaignCreateForm.tsx
  resources/js/Components/Form/index.ts
  resources/js/Components/Table/CampaignTable/CampaignTable.test.js
  resources/js/Components/Table/CampaignTable/CampaignTable.tsx
  resources/js/Components/Table/CampaignTable/index.ts
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/Table/index.ts
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Campaign/Campaign.test.js
  resources/js/Pages/Campaign/Campaign.tsx
  resources/js/Pages/Campaign/Create/CampaignCreate.tsx
  resources/js/Pages/Campaign/Create/index.ts
  resources/js/Types/campaign-data.ts
  resources/js/Utils/formatter.ts
  resources/js/Utils/index.ts
  resources/mock/campaign-data.ts
  tests/Feature/Http/Controllers/CampaignControllerTest.php
Labels: task, front end

#415 Event Reports Cypress Test
  app/Actions/FulfillTrade.php
  app/Exceptions/TradeClosedException.php
  app/Exceptions/TradeNotAllowedException.php
  app/Http/Controllers/TradeFulfillmentController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/TradeFulfillRequest.php
  app/Http/Requests/UserUpdateRequest.php
  app/Models/User.php
  app/Policies/TradePolicy.php
  app/Providers/AuthServiceProvider.php
  cypress/integration/Event Management/event_reports.js
  cypress/plugins/index.js
  database/migrations/2022_02_18_221110_add_language_to_users_table.php
  resources/js/Components/Authentication/Authentication.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Profile.tsx
  resources/js/Types/global.ts
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
  routes/web.php
  tests/Feature/Http/Controllers/TradeFulfillmentControllerTest.php
  tests/Feature/Http/Controllers/UserControllerTest.php
  tests/Unit/Actions/FulfillTradeTest.php
Labels: test

#414 Campaign Details Page
  app/Http/Controllers/CampaignController.php
  resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
  resources/js/Components/Detail/CampaignDetail/index.ts
  resources/js/Components/Detail/index.ts
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/index.ts
  resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
  resources/mock/entries-data.ts
  tests/Feature/Http/Controllers/CampaignControllerTest.php
Labels: enhancement, front end

#422 Fix missing Cypress Test
  cypress/integration/Event Management/event_reports.js
Labels: chore

#427 Loading button
  resources/js/Components/Atom/Button.tsx
  resources/js/Components/Atom/index.ts
  resources/js/Components/Authentication/Authentication.tsx
  resources/js/Components/Form/CharacterImportForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Profile.tsx
Labels: task, front end

#429 Event index page
  app/Http/Controllers/EventController.php
  resources/js/Components/Table/EventTable/EventTable.test.js
  resources/js/Components/Table/EventTable/EventTable.tsx
  resources/js/Components/Table/EventTable/index.ts
  resources/js/Components/Table/index.ts
  resources/js/Components/index.ts
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Event/Event.test.js
  resources/js/Pages/Event/Event.tsx
  resources/js/Pages/Event/index.ts
  resources/js/Pages/Welcome.tsx
  resources/js/Types/event-data.ts
  resources/js/Types/league-data.ts
  resources/mock/event-data.ts
  tests/Feature/Http/Controllers/EventControllerTest.php
Labels: enhancement, task, front end, test

#441 English/French translations + edit drawer error handling
  cypress.json
  cypress/integration/Character Management/character_exploration.js
  cypress/integration/Character Management/item_management.js
  cypress/integration/Game Session Tracking/dm-entry-management.js
  cypress/integration/Game Session Tracking/entry_management.js
  cypress/integration/Game Session Tracking/item_entry_management.js
  package.json
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Atom/DataTable.tsx
  resources/js/Components/Atom/Select.tsx
  resources/js/Components/Authentication/Authentication.tsx
  resources/js/Components/Chips/RarityChip/RarityChip.tsx
  resources/js/Components/DeleteModal/DeleteModal.test.js
  resources/js/Components/DeleteModal/DeleteModal.tsx
  resources/js/Components/Detail/CharacterDetailBox.tsx
  resources/js/Components/Detail/ItemDetailBox.tsx
  resources/js/Components/Form/BulkEntryCreateForm.tsx
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/CharacterImportForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.test.js
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.test.js
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Form/ItemEditForm.test.js
  resources/js/Components/Form/ItemEditForm.tsx
  resources/js/Components/Form/ItemForm.tsx
  resources/js/Components/Form/LoginForm.tsx
  resources/js/Components/Form/RatingForm.tsx
  resources/js/Components/Form/RegistrationForm.tsx
  resources/js/Components/Table/CharacterTable/CharacterTable.tsx
  resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
  resources/js/Components/Table/EntryTable/EntryTable.tsx
  resources/js/Components/Table/ItemTable/ItemTable.tsx
  resources/js/Components/Table/RatingTable/RatingTable.tsx
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.test.js
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
  resources/js/Pages/Character/Character.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/DMEntry/DMEntry.tsx
  resources/js/Pages/Item/Detail/ItemDetail.tsx
  resources/js/Pages/Item/Item.tsx
  resources/js/Pages/Profile.test.js
  resources/js/Pages/Profile.tsx
  resources/js/Pages/Rating/Rating.tsx
  resources/js/Pages/Welcome.tsx
  resources/js/Utils/option-constants.ts
  resources/js/Utils/theme.test.js
  resources/js/Utils/theme.ts
  resources/js/Utils/use-user.ts
  resources/js/app.js
  setup_jest.js
  tsconfig.json
  webpack.config.js
  yarn.lock
Labels: bug, enhancement, front end

#452 Update french translations
  public/translation_fr.json
Labels: enhancement

#456 Add campaign field to entry creates
  app/Http/Controllers/CharacterController.php
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  app/Http/Requests/EntryStoreRequest.php
  app/Http/Requests/EntryUpdateRequest.php
  app/Models/Campaign.php
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
  resources/js/Components/Table/CampaignTable/CampaignTable.tsx
  resources/js/Pages/Campaign/Campaign.tsx
  resources/js/Pages/Character/Detail/CharacterDetail.tsx
  resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
  resources/js/Pages/DMEntry/DMEntry.tsx
  resources/js/Pages/Entry/Create/DmEntryCreate.tsx
  resources/js/Types/entries-data.ts
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: enhancement, back end, front end

#459 Change Username Font
  cypress/integration/Authentication/authentication.js
  cypress/support/commands.js
  public/translation_en.json
  public/translation_fr.json
  resources/js/Components/Authentication/Authentication.test.js
  resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
Labels: bug, front end, design

#457 Return to step 1 when there is error for edit drawers
  resources/js/Components/Form/CharacterCreateForm.tsx
  resources/js/Components/Form/DmEntryCreateForm.tsx
  resources/js/Components/Form/EntryCreateForm.tsx
Labels: bug, front end

#454 Add new event accessors
  app/Models/Event.php
  tests/Unit/Models/EventTest.php
Labels: task, back end, priority

#462 Entry create endpoint extension
  app/Http/Controllers/DMEntryController.php
  app/Http/Controllers/EntryController.php
  tests/Feature/Http/Controllers/DMEntryControllerTest.php
  tests/Feature/Http/Controllers/EntryControllerTest.php
Labels: back end

#460 Add campaign ownership flag
  app/Http/Controllers/CampaignController.php
  app/Http/Controllers/CampaignRegistrationController.php
  app/Models/Campaign.php
  app/Models/User.php
  database/migrations/2022_02_27_224955_add_is_owner_to_campaign_user_table.php
  tests/Feature/Http/Controllers/CampaignControllerTest.php
  tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php
Labels: enhancement, task, back end
